Steps to manage purchase
- [ ] Eng- Identify Suppliers for project
- [ ] GP- Validate if suppliers in IBM Vendor List or Compro Vendor list
- [ ] Eng- Specs written/approved by Engineers  (Appendix E)
- [ ] GP- Formal RFQ created and sent to ALL suppliers
- [ ] GP- Receive RFQs
- [ ] ALL- Review RFQs with Engineers
- [ ] ALL- Select Supplier
- [ ] GP- Equipment Agreement created/updated with Supplier
- [ ] GP-Source file needed (Over $500K?)
- [ ] ENG- Bond Cart created by requester
- [ ] ENG- Bond Cart Approved (MGR, Capital, WWCT approvals)
- [ ] GP- Equipment Agreement agreed/signed by IBM and Supplier?
- [ ] GP- Send Supplier PO
